version: '3'

services:
  db_owncloud:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_owncloud:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=passwd
    networks:
      - intranet

  http:
    container_name: http_container
    depends_on:
      - db_owncloud
    build: ./http
    restart: always
    ports:
      - 443:443
    volumes:
      - /var/www/html/:/var/www/html/file:ro
      - /etc/letsencrypt/live/Here_should_be_your_domain_name/privkey.pem:/ssl/privkey.pem:ro
      - /etc/letsencrypt/live/Here_should_be_your_domain_name/fullchain.pem:/ssl/fullchain.pem:ro 
      - /var/www/owncloud:/var/www/html/owncloud
    networks:
      - intranet

volumes:
  db_owncloud:

networks:
  intranet:
